wikidb:
  image: mongo
  container_name: wikidb
  restart: unless-stopped
  expose:
    - "27017"
  command: '--smallfiles --logpath=/dev/null'
  volumes:
    - $PWD/volumes/data/mongo:/data/db
wiki:
  image: heamon7/wiki
  container_name: wiki
  build: .
  restart: unless-stopped
  links:
    - wikidb
  # stdin_open: true
  # tty: true
  ports:
    - "3001:3000"
    - "81:80"







  